services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  celery:
    build: .
    command: celery -A onlineshopping worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - C_FORCE_ROOT=True
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # برای ارتباط با Celery
      - "15672:15672"     # پنل مدیریتی وب
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - your_network_name

volumes:
  rabbitmq_data:

networks:
  your_network_name:
    driver: bridge
  
  flower:
    build: .
    command: celery -A onlineshopping flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    volumes:
      - .:/code
  beat:
    build: .
    command: celery -A onlineshopping beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq