services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - backend
    env_file:
      - .env

  celery:
    build: .
    command: celery -A onlineshopping worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - C_FORCE_ROOT=True
    depends_on:
      - rabbitmq
    networks:
      - backend
    env_file:
      - .env

  flower:
    build: .
    command: celery -A onlineshopping flower
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
    volumes:
      - .:/code
    networks:
      - backend
    env_file:
      - .env
  beat:
    build: .
    command: celery -A onlineshopping beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    networks:
      - backend
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"       # برای ارتباط با Celery
      - "15672:15672"     # پنل مدیریتی وب
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    env_file:
      - .env

volumes:
  rabbitmq_data:

networks:
  backend:
    driver: bridge
  
